package dmitry.polyakov.constants;

public enum BotStateEnum {
    DEFAULT_STATE,
    ASK_PHRASE,
    WRITING_WORDS,
    READING_DICTIONARY,
    SETTINGS,
    READING_PHRASE,
    SEARCHING_PHRASE,
    CONFIRM_REMOVAL,
    LANGUAGE_CHANGE,
    SETTINGS_NUMBER,
    SETTINGS_ORDER,
}
